version: '3'

services:
  api:
    image: "menju_image:latest"
    build: .
    container_name: "mengju_container"
    ports:
      - "8192:8192"
    networks:
      - myNetwork
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512m
          
networks:
  myNetwork:
    driver: bridge